### PR TITLE
Add locate me

### PR DESCRIPTION
**Pull request by jonahadkins**
this adds enhancement #144 for a locate me feature

### CODE REVIEW

**Comment by jonahadkins** [comment]
my first time installing node, grunt, etc  - contribution instructions were great! :100: 

locate feature references locate cdn with top left location - will need to add to css file for custom location.

**Comment by mapsam** [comment]
Sweeeeeeet! Thanks for doing this :dancer: I'm working on a big overhaul in the `alpha` branch right now, which might mean the `leaflet-locatecontrol` will be installed differently at some point (via `npm` instead of CDN), but hot diggity glad you were able to add it! 

Not sure why the checks are failing here, though.

**Comment by alukach** [comment]
Will this add the location as a layer or only zoom to a persons location?  It looks like just the latter? I think both are valuable, so thanks for putting this in!

**Comment by mapsam** [comment]
Ohhh location as a layer would be awesome.

**Comment by jonahadkins** [comment]
Just zooms to the persons location :disappointed: - the users location can probably be obtained from the marker or centroid extent, but that's beyond my skills (for now). 

i wasn't sure where to add the library to the project - there are a few css properties we can use to move the locate me button underneath the zoom in/out control.

**Comment by mapsam** [comment]
No sad faces! This is all :smile:s. I've noted "turn user location into layer" as a bonus feature in the alpha and it can be unrelated to this PR.

As for adding libraries, we've gone back and forth between using CDNs, `npm` & bundle, and `require()` in our files. I'm leaning towards `npm` & bundle because it lands in the middle of efficient and manual. [Here's what it looks like](https://github.com/cugos/dropchop/blob/alpha/gulpfile.js#L34-L40) in the `alpha` branch right now after you `npm install XXXXXXX --save` and bundle it.

**Comment by jonahadkins** [comment]
ill wire it up to use npm & bundle :+1:

**Comment by mapsam** [comment]
Cool!

**Comment by mapsam** [comment]
Hey @jonahadkins it looks like there is a relatively quick way to do this using the `locate()` function in `mapbox.js`. https://www.mapbox.com/mapbox.js/example/v1.0.0/geolocation/ - might not need to introduce another library! This also returns geometry, which could be used subsequently to make a new layer.

**Comment by jonahadkins** [comment]
Even better - Ill work on that then

**Comment by jonahadkins** [comment]
currently having beginner issues with [this._map.locate();](https://github.com/jonahadkins/dropchop/blob/add_location_%23144/src/js/mapview/MapView.js#L54)  throwing a `Uncaught TypeError: Cannot read property 'locate' of undefined` error

**Comment by npeihl** [comment]
@jonahadkins I wonder if the `this` variable isn't available in the function due to closure issues? Unfortunately, I'm not sure what the best way to handle `this` is. Maybe @mapsam or @alukach have ideas.

**Comment by alukach** [comment]
@jonahadkins Haven't had a time to actually checkout your code, but it sounds likes you `this` object isn't what you think it is in that function.  It's an awkward JS issue that is can bit strange if you haven't experienced it before. The error you posted is basically saying that `this._map` is `undefined`.  Basically, `this` refers to the scope within that `function (e)` that you're defining, so it won't be the same as the `this` on the lines above.  There are two common ways to fix this:

* Create a point of `this` outside of the function that won't be overwritten when you enter the function. ie:
```javascript
if (!navigator.geolocation) {
    geolocate.innerHTML = 'Geolocation is not available';
} else {
    var _this = this;  // Assigning the old 'this' to a variable that won't be overwritten
    geolocate.onclick = function (e) {
        e.preventDefault();
        e.stopPropagation();
        _this._map.locate();  // Explicitely using the old 'this'
    };
}
```
* Use [`bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) to tell the function to use the class' `this`:
```javascript
if (!navigator.geolocation) {
    geolocate.innerHTML = 'Geolocation is not available';
} else {
    geolocate.onclick = function (e) {
        e.preventDefault();
        e.stopPropagation();
        this._map.locate();
    };
}.bind(this)
```

I'm no expert, but I feel like either of those should help.  I think option 2 is a bit cleaner.

Ps. Watch out for the indentation in that class. It's functionally the same, but a well indented chunk of code is much easier to read.

**Comment by mapsam** [comment]
Yes, thanks @alukach! The confusion of `this` is mostly a relic in the `alpha` branch, which makes jumping into the code a bit more straightforward. 

It will look more like this in `alpha`, with `dc` being short for `dropchop`:

```JS
var myLocation = dc.map.m.locate() // can use this anywhere, without referring to "this"
```

**Comment by jonahadkins** [comment]
omg y'all *IT WORKS*

i get a warning from chrome dev tools:

`getCurrentPosition() and watchPosition() are deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.`

**Comment by mapsam** [comment]
*aw paying money for https:// sounds like a fun way to spend my day*

**Comment by alukach** [comment]
So, allegedly you can set up SSL w/ custom domains for free: https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/.  Will add an issue.

**Comment by mapsam** [comment]
Whoa. Nice!

**Comment by jonahadkins** [comment]
FYI - Everything Works - I think the button might need some JS help to stay put (the previous library we used did) 
What else can I do / need to do on this branch?

**Pull request merged**
