### PR TITLE
TopoJSON

### PR DESCRIPTION
**Pull request by jczaplew**
Added the ability to add and export TopoJSON as outlined in #201. The main changes are as follows:

**Front**
+ Added a button to the `save` menu to save as TopoJSON
+ Added ability to add a TopoJSON file by dragging and dropping, from a gist, or from a URL

**Back**
+ Added a new dependency - `topojson`
+ Added three new dev dependencies - `browserify`, `vinyl-source-stream`, and `vinyl-buffer`
+ In order to use the server API on the client side for saving to TopoJSON, a new script was added `lib/topojson_setup.js` that creates a global object for both the client and server API. However, for now only the `topology` function from the server API was added so that unnecessary methods are not included. It is then run through `browserify` and included in `vendor.js`.

It'd be nice to add tests as well, but it seems like there are not currently tests for this part of DC (though perhaps there should be?). Thoughts?

### CODE REVIEW

**Comment by jczaplew** [comment]
It seems like the tests are failing because TopoJSON uses Float64Arrays and phantomjs does not support them because it uses a super old version of webkit - https://github.com/ariya/phantomjs/issues/10607

**Comment by jczaplew** [comment]
I'm not sure why this test failed -- https://travis-ci.org/cugos/dropchop/builds/87390329

I just tried it with node 0.12.7 on my local machine and it worked fine. Has anyone else seen that error?

**Comment by jczaplew** [comment]
There we go! Now that things are passing, any objections to merging into master?

**Comment by mapsam** [comment]
:+1:

**Pull request merged**
