### PR TITLE
Layerlist ui

### PR DESCRIPTION
**Pull request by svmatthews**
@alukach I added a few loops in the click functions for layer list items that begin to add functionality for holding shift to select multiple layers. I also added the `metaKey` (command on a mac) that allows you to select other individual layers.

**NOTE: This is being merged into your `refactor-layerlist` branch since I didn't want to conflict off of master**.

Here's a gif:

dnc-shiftselect

### CODE REVIEW

**Comment by alukach** [comment]
Wow, fast turn around, nice! Looks really good from the GIF.  Thanks for branching off of my refactor, that makes life easier.  I'll get those tests passing ASAP.

**Comment by alukach** [comment]
@svmatthews Merged in my fixes to tests, although looks like this change has resulted in one test failure.

**Comment by svmatthews** [comment]
Just merged in changes from `refactor-layerlist` and am getting one error:

```
PhantomJS 1.9.8 (Mac OS X) L.DNC.LayerList _handleLayerClick LayerList._handleLayerClick if the target is already selected FAILED
```

**Comment by alukach** [comment]
Yup, that's the one that I was referring to. It appears that something in
this PR has broken the test.

Options:

   - You fix it
   - I fix it
   - We pair and do it together via google hangout to make sure we're on
   the same page w/ testing.

**Comment by svmatthews** [comment]
I choose door 3!

**Comment by svmatthews** [comment]
closing and reopening as new PR into `master`

**Pull request closed without merging**
