### PR TITLE
Sample

### PR DESCRIPTION
**Pull request by wboykinm**
Add `turf-sample` to the configured functions, per #265

### CODE REVIEW

**Comment by wboykinm** [comment]
@mapsam I was just digging through tests and noticed that none in the spec seem to operate on the turf functions themselves. Is there a handler or helper for input/output geojson? Even something as simple as getting a response for `expect(outGeoJson.features.length).to.equal(whatever);`?

**Comment by nickpeihl** [comment]
@wboykinm I think best practices says that the owners of the Turf library should be responsible for testing the Turf functions and we should give them the benefit of the doubt on the validity of those functions.

**Comment by wboykinm** [comment]
@nickpeihl Coolness - what then is the policy around here about merging one's own PRs?

**Comment by nickpeihl** [comment]
The only policy we have is http://cugos.org/code-of-conduct/ which doesn't address this specifically. This isn't a breaking change so I say you're gtg if you are happy with it.

**Comment by mapsam** [comment]
Lovely. @wboykinm it's always nice to have a gif/screenshot of what's being added - if that's something you're able to do!

**Comment by wboykinm** [comment]
sample

**Comment by wboykinm** [comment]
Whoops. Totally forgot the changelog and version. Coffee hasn't sunk in yet.

**Comment by mapsam** [comment]
@wboykinm since we don't have a completely robust release mechanism - I've, more than once, committed the version/changelog updates straight into master. shhhh 😄 (Don't think less of me!)

**Comment by wboykinm** [comment]
@mapsam I was hoping exactly the same. Some devops engineer is scowling at me right now, surely.

**Pull request merged**
