### PR TITLE
Starting to get file saving to work.  The shapefile saver is kind of …

### PR DESCRIPTION
**Pull request by mapsam**
…flaky from mapbox and is just as flaky on geojson.io... but it is a start.  We use a try catch statement for the export of the shapefiles... so if they fail at least we display a warning and move on.  Export to geojson works much more consistently.  In the geojson case we export each layer separately and increment the name of the file. This is for issue #11

@aaronr opening this to start working on tests

### CODE REVIEW

**Comment by mapsam** [comment]
@alukach this is going to need some love with your refactor from #117

**Comment by alukach** [comment]
Yeah, looks like we both made `FileExecute.js` (and some others).  Will do a merge when I get a chance.

**Comment by aaronr** [comment]
I am happy to revisit this... but the longer we wait the more merge conflicts we will get.  I was still unclear if you wanted me to back out the inclusion of the web ready dependencies I added in favor of switching our whole system to Browserify.  Seems to me getting this in as is makes more sense and then add (or re-open) a ticket to go in and add Browserify support back in.  Then finally a ticket to move the existing download stuff to utilize browserify instead of the static includes.  Doing all of this at once seems a bit hard to keep a handle on.

**Comment by alukach** [comment]
I guess this begets the question: should the Save tooling go down under the LayerList?  If not, should the Load File go up in the `File` menu?

@aaronr Agreed that Browserify refactor doesn't need to be a part of this PR

**Comment by mapsam** [comment]
I regret pushing that commit ...

**Comment by alukach** [comment]
Why the regret?  The merge looked okay to me.

**Comment by mapsam** [comment]
@alukach @aaronr this is all working now - I've added a mock test file to fill out. Might need some help with this one. (like every test)

**Pull request merged**
