### PR TITLE
adding turf functions

### PR DESCRIPTION
**Pull request by mapsam**
Going to clean up some issues here:

- [x] TURF: Add midpoint operation #90
- [ ] ~~TURF: Add extent operation #89~~
- [x] TURF: Add destination operation #87 
- [x] TURF: Add along operation #85 
- [x] TURF: Add explode operation #84 
- [x] TURF: Add simplify operation #82

### CODE REVIEW

**Comment by mapsam** [comment]
Adding midpoint:

dropchop-midpoint

**Comment by mapsam** [comment]
Destination:

dropchop-destination

**Comment by mapsam** [comment]
`along`

dropchop-along

**Comment by mapsam** [comment]
`explode`

dropchop-explode

**Comment by mapsam** [comment]
Hmmm, stuck at the end with `simplify`. I've written tests and they pass, but when I execute the function in the app the feature is only replicated, and not simplified.

**Comment by alukach** [comment]
@mapsam Took a look at `simplify`, seems like there were two problems:

1. We were using `parseInt` rather than `parseFloat` for any number input, meaning that any `tolerance` < `1` would be `0`. Effectively, disabling it.
1. Using a `select` for a boolean seems a bit weird. The value that comes from a `select` is always a string. We could do something like `if (value == 'false' || 'true') value = parse(value);`, but I still feel like a `checkbox` is a better representation of a boolean.

Before:
bad-simplify

After:
good-simplify

**Comment by mapsam** [comment]
Nice debugging! Thanks for adding some extra love to this. Agreed on checkbox considering there are other functions that will have options like this.

Considering this ready to merge if it looks good to you.

**Comment by alukach** [comment]
Done, good work on this!

**Pull request merged**
