### PR TITLE
Update INSTALLATION.md

### PR DESCRIPTION
**Pull request by thedeb**
Updated INSTALLATION.md with some notes tailored for Windows.

### CODE REVIEW

**Comment by npeihl** [comment]
@thedeb It's a Monday, so forgive me if this is a stupid question. Why is Python needed for Dropchop?

**Comment by thedeb** [comment]
Hi Nick,
I thought we saw a dependency when installing npm on Windows, I think it was. @mccombsp-kingco, is that right?
Thank you for checking my work.

**Comment by mapsam** [comment]
Looks like there are some [other python-related install issues on Windows](http://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies). This is a really weird barrier, and really has nothing to do with dropchop at all.

I'm honestly kind of surprised python isn't installed on Windows machines natively?

**Comment by mccombsp-kingco** [comment]
Microsoft doesn't expect all users to be developers. Esri users will have
it installed, most others won't.

**Comment by npeihl** [comment]
@mccombsp-kingco I guess that's why I didn't have any issues. I was testing it on my work machine (Esri software installed). Thanks.

**Comment by mapsam** [comment]
Good point!

Seems like most of the issues out there with Windows and `npm` deal with [`node-gyp`](https://www.npmjs.com/package/node-gyp) and the environment variable not existing. Not sure if there's anything we can do other than make a comment in the install docs like @thedeb has already done.

**Comment by npeihl** [comment]
I'm satisfied with @thedeb's and @mccombsp-kingco's  work and suggest we merge. :100:

**Comment by mapsam** [comment]
Agreed! :100: 

Looks like we are getting a timeout due to the size of `js_vendor` in `gulp-uglify`. Not entirely sure how to prevent this.

**Comment by mapsam** [comment]
Confirmed the error exists for all tests, in #248

**Pull request merged**
