### PR TITLE
pulling colors into variables

### PR DESCRIPTION
**Pull request by mapsam**
This PR adds a thematic color scheme to dropchop (not definite, but was good to work with) and pulls a lot of our shared variables into the `_variables.scss` file so we can update styles easily without having to skim through a ton of `.scss` files.

screen shot 2015-06-17 at 12 07 14 am

### CODE REVIEW

**Comment by mapsam** [comment]
Aww man, why did this fail!?

**Comment by alukach** [comment]
Looks good to me!

**Comment by mapsam** [comment]
Woop! I also added a couple more fonts, a monospace and a new sans-serif (Roboto). Mostly, I was getting sick of staring at what we had :wink:

**Comment by alukach** [comment]
One concern that I have with this color palette is that it may possibly clash-with/influence the visual styling of data that a user may want to add (assuming #126 and #130 get employed).  I think the data and base-layer itself should be the primary focus from a user's perspective (which is something that a really neutral palette supports well).

I do like the aesthetics of this, but if I'm processing and styling data that I intend to put on my orange-themed red-toned site, these colors could make it more difficult to mentally visualize what the styled data will look like when I put it on my website.

**Comment by mapsam** [comment]
Good point. I'm going to push back a little on this one, just because doing this styling stuff is what's getting me excited right now. Since everything is broken into the `_variables.scss` file we can make changes quickly. We could even allow the user to switch between bold/light versions.

**Pull request merged**
