### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by jonahadkins**
hi! :wave: 
are ya'll wanting gif-only explanations in the readme or gif + text? 
this pr is for issue #239

### CODE REVIEW

**Comment by alukach** [comment]
GIFs are definitely a +1. Are there any caveats that a user should be aware of?  This feature is pretty clear in concept so a lot of text probably isn't too crucial, maybe just that it "Adds the users location as a Point feature layer.  The user must grant Dropchop permission to use its location to generate the layer" or something like that?

**Comment by jonahadkins** [comment]
Can Do - i can run some gif's for each function on toolbar if that will help :+1:

**Comment by npeihl** [comment]
I wonder if it would be useful to include a link to the [W3 Geolocation API Specification](http://www.w3.org/TR/geolocation-API/), or is that unnecessary?

**Comment by jonahadkins** [comment]
this pr now includes descriptions and gifs for #234 #235 #236 #237 #238 #239  

should be a good start :+1:

**Comment by alukach** [comment]
Woah! Above and beyond @jonahadkins! Definitely a good start!

@npeihl Not sure how technical we should get. I see this as being a starting location for a user's manual (rather than a developer's manual).  Eventually, we'll probably want to serve this data as a view in the app itself.  Maybe in the future we should think about adding developer's notes to each feature as well?

**Pull request merged**
