### PR TITLE
Fix load-arcgis function with new UI

### PR DESCRIPTION
**Pull request by npeihl**
Whoops! The `load-arcgis` button was lost in the latest UI changes.

### CODE REVIEW

**Comment by alukach** [comment]
Sorry @npeihl! Undoubtedly a merge failure on my part!

**Comment by mapsam** [comment]
@npeihl realized you weren't added to the contributors group for this repo - you should be able to make branches straight on this repo now, without having to fork. Sorry that took a long time!

**Comment by npeihl** [comment]
@alukach: No problem. Merge conflicts aren't easy.

@mapsam: Whoohoo! Thanks!

**Comment by mapsam** [comment]
Did we also lose the "save a topojson" feature? @jczaplew @alukach

**Comment by alukach** [comment]
@mapsam @jczaplew Ooops, I think that did get skipped as well. Re-added with a408b95 (hopefully).

**Comment by mapsam** [comment]
:+1: thanks!

**Pull request merged**
