### PR TITLE
Modularize

### PR DESCRIPTION
**Pull request by wboykinm**
Per #261, replace turf-the-monolith with individual modules as they are configured.

### CODE REVIEW

**Comment by wboykinm** [comment]
@mapsam This looks GTG.

**Comment by mapsam** [comment]
Hey! Nice work @wboykinm 😄 

Updated docs ❤️ 

For the sake of semver, I think staying within `0.2.x` is fine here, since we are only changing dependencies, and functionality won't change/update at all for the end user. `0.2.3` should be 👍

**Comment by mapsam** [comment]
Also sent you an invite to the CUGOS org and dropchop team so you don't have to keep forking!

**Comment by wboykinm** [comment]
I have the worst time speaking semver :)

**Comment by wboykinm** [comment]
@mapsam Okay - bumped back the version. Thanks for the invite! I'll make future changes from upstream.

**Comment by mapsam** [comment]
Beautiful. Merging 👍

**Comment by mapsam** [comment]
Confirmed we are live!

screen shot 2016-08-03 at 10 06 33 am

**Pull request merged**
