### PR TITLE
Add/remove layer buttons

### PR DESCRIPTION
**Pull request by alukach**
## Description

As per #117, add some controls at the bottom of the layerlist to add and remove layers. The 'add' control is a menu, exposing operations to add a file in different ways.  The 'remove' control should be an operation itself, rather than a menu (I can only think of a single way that remove would work). This is a bit of a departure from the current menu capabilities, as a menu bar only allows the containment of menus, not operations.

bottom-menu

## What's Changed

- The direction in which a `menu-dropdown` appears in relation to a `menu` is now driven by the `menu` options.
- `div#dropzone` -> `div#sidebar`
- `.menu-dropdown` has `z-index` of `1`, to overlap `map`

## To do
@svmatthews curious what you think about the UI of the button and it's placement. Not super crazy about it and very open to hear suggestions about how to improve it.

- [x] Add tooling to allow remove button to be added to menubar (rather than adding menu to menubar)
- [x] Allow operation to not have intermediary form
- [x] Add upload file tooling
- [x] Add import file tooling
- [x] Wire remove button to remove item from layerlist / map

### CODE REVIEW

**Comment by svmatthews** [comment]
Nice workin! As far as the UI goes, I'm not too concerned about it right now. We haven't really made any decisions as far as the design so far. I think eventually all of these will have to turn into icons with tooltips, but that's a ways down the road (maybe?).

How does upload from URL work?

**Comment by alukach** [comment]
@svmatthews Does an ajax request to a provided URL and fetches the data.
uploadfromurl

It's in efforts of moving the project to allowing DC to act as a data viewer/editor.  I'd really like to get to a point where a user could access http://dropchop.io/?url=https://gist.githubusercontent.com/alukach/0bf4471e44a0243b66db/raw/39a3ad702cf08af1d5aeb606a098a0b4a4477033/union1.geojson, which would load the file automatically.  This would allow people to easily have "Edit this file with DropChop" links, if someone so chooses.

**Comment by svmatthews** [comment]
:boom: !!! That's awesome.

Agreed on all of the above.

**Comment by alukach** [comment]
Alright, I believe that this had reached feature complete.

completed

There were some notable changes to the operations, forms, and menu classes:

- Loading files via AJAX required that the operations be asynchronous. Execution class (`GeoExecute` and `FileExecute`) `execute()` methods now take in a callback as an arg and pass results to that callback, rather than returning the results.
- Rather than returning a single layer, operations pass (to the callback) a result package. This is an object that describes what the callback should do with a given feature. Currently, it only supports `add` and `remove`.  If you were to remove two layers and add one (such as if there were a merge operation), you would return `{add: [newLayerObj], remove: [oldLayerObj1, oldLayerObj2]}`. `_handleResults` then handles these layers accordingly.  I could imagine an `update` action being added, or a `notify` action to handle operations that have no geo-results (such as `count`). As such, operations no longer need the `createsLayer: true` property.
- Forms intake an `extra` param from an operation parameter config, which appends whatever string given into the generated input.
- Forms can be skipped if the operation parameter has the `disableForm: true` setting.
- You can give menubars custom classes (used to push menubar to bottom of layerlist)
- You can provide a menu a custom icon class via the `iconClassName` option.
- If a menu has no sub-items, it is treated as a button (such as the 'remove' button).

This still requires a few tests but is ready to test.  Will comment again when tests are complete.

**Comment by mapsam** [comment]
:clap: @alukach!

**Comment by alukach** [comment]
This guy still needs some testing, I'll make an issue for it.

**Comment by mapsam** [comment]
Oh, sorry! I read "feature completion" as ... complete.

**Pull request merged**
