### PR TITLE
Put documentation into project files

### PR DESCRIPTION
**Pull request by alukach**
As mentioned in #190, I think we should put as much documentation into the actual repo as possible.  This allows for documentation to be added as part of Pull Requests and pins to the documentation to the checked-out version of code.

## README.md

As features grow, I think it's going to be important to add descriptions of each feature so that users can be made aware of all of Dropchop's potential.  Placing these in the README.md file would probably provide the most visibility of these docs (eventually they should probably be rendered in the application itself). I put in the following sections into the README file:

* Adding Data
  * Upload
  * URL
  * Open Street Map
  * Gist
  * ArcGIS Server Feature Service
  * User Location
* Exporting Data
  * GeoJSON
  * Shapefile

If approved, I'll make an Issue for each of those sections and nudge the developer who implemented that feature.

## CONTRIBUTING.md

I've moved all of the documentation about Dropchop's inner workings (signals, adding turf) into the CONTRIBUTING.md file.  I've also added some notes about Collaborating, Prereqs, Documentation, They feel a bit forced in there and could possibly be moved into a separate file (not sure what that would be called).  Additionally, I feel like describe what is passed with each signal and what each signal is used (that would be another Issue).

## CHANGELOG.md

It seems like the CHANGELOG.md doc is a bit out of date, anyone want to go in and update that from the merged PRs?

## INSTALLATION.md

Moved the installation docs into INSTALLATION.md.

If approved, I'd suggest that we delete the duplicate documentation from the wiki.

### CODE REVIEW

**Comment by mapsam** [comment]
Excellent. I think this is great!

**Comment by alukach** [comment]
Great, going to go ahead and merge.

**Comment by alukach** [comment]
Fun fact, adding the `CONTRIBUTING.md` adds this link to all PRs:

screen shot 2015-11-08 at 10 31 47 pm

**Comment by mapsam** [comment]
Ha, awesome.

**Pull request merged**
